### ISSUE TITLE
Wrong literals in function call

### ISSUE THREAD

**Issue by JKathmann** [im-oxygen/libaria2-ts#4]
https://github.com/hyroge/libaria2-ts/blob/00a8265fdd8946b16b1ff93296df0b4df121cf8d/src/adapter.ts#L179-L184
Line 181 should be replaced with:
`"aria2.getFiles",`

https://github.com/hyroge/libaria2-ts/blob/a070137aa5d1090b27354339fa82c9c47d75dd84/src/adapter.ts#L200-L207
Line 202 should be replaced with:
`"aria2.getServers",`

**Comment by hydrati** [comment]
thanks, i will fix  it

**Comment by hydrati** [comment]
it fixed in ecc8f786b8ae16d2e571f7e24bcc600c52b9ae74
